package com.example.maddbtestapp2

import android.content.Intent
import android.os.Bundle
import android.widget.AdapterView
import android.widget.ArrayAdapter
import android.widget.Button
import android.widget.CalendarView
import android.widget.Spinner
import android.widget.TimePicker
import androidx.appcompat.app.AppCompatActivity
import com.example.maddbtestapp2.appointment.Appointment
import com.example.maddbtestapp2.appointment.AppointmentQueries
import com.example.maddbtestapp2.databaseConfig.DbConnect
import com.example.maddbtestapp2.vaccine.Vaccines
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import java.sql.Date
import java.sql.Time
import java.util.*

class ScheduleAppActivity : AppCompatActivity() {

    private lateinit var vaccineSpinner: Spinner
    private lateinit var datePicker: CalendarView
    private lateinit var timePicker: TimePicker
    private lateinit var saveButton: Button

    private var selectedVaccine: Vaccines? = null
    private var selectedDate: Long = 0
    private var selectedTime: String = ""

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_schedule_app)

        vaccineSpinner = findViewById(R.id.vaccPicker)
        datePicker = findViewById(R.id.datePickerSchd)
        timePicker = findViewById(R.id.timePickerSchd)
        saveButton = findViewById(R.id.btnSave2)

        val date1 = Date.valueOf("2024-06-06")
        val date2 = Date.valueOf("2024-08-06")
        val date3 = Date.valueOf("2024-12-04")
        val date4 = Date.valueOf("2024-12-07")

        val vaccines = listOf(
            Vaccines(1, "Vaccine 1", date1, date2),
            Vaccines(2, "Vaccine 2", date3, date4)
        )
        val adapter = ArrayAdapter(this, android.R.layout.simple_spinner_item, vaccines.map { it.vaccineName })
        adapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item)
        vaccineSpinner.adapter = adapter

        vaccineSpinner.onItemSelectedListener = object : AdapterView.OnItemSelectedListener {
            override fun onItemSelected(parent: AdapterView<*>, view: android.view.View?, position: Int, id: Long) {
                selectedVaccine = vaccines[position]
            }

            override fun onNothingSelected(parent: AdapterView<*>) {
                selectedVaccine = null
            }
        }

        datePicker.setOnDateChangeListener { _, year, month, dayOfMonth ->
            val calendar = Calendar.getInstance()
            calendar.set(year, month, dayOfMonth)
            selectedDate = calendar.timeInMillis
        }

        timePicker.setOnTimeChangedListener { _, hourOfDay, minute ->
            selectedTime = String.format("%02d:%02d", hourOfDay, minute)
        }

        saveButton.setOnClickListener {

            // Create an Appointment object with the selected data
            val appointment = Appointment(
                id = 0, // Assuming the ID will be generated by the database
                userId = 0, // Replace with the actual user ID
                vaccineId = selectedVaccine?.id ?: 0, // Ensure a vaccine is selected
                date = Date(selectedDate),
                time = Time.valueOf(selectedTime)
            )

            // Insert the appointment into the database
            CoroutineScope(Dispatchers.IO).launch {
                val connection = DbConnect.getConnection()
                val appointmentQueries = AppointmentQueries(connection)
                appointmentQueries.insertAppointment(appointment)
                connection.close() // Close the connection when done
            }

            // Redirect to MainActivity after saving
            val intent = Intent(this, MainActivity::class.java)
            startActivity(intent)
        }
    }
}
//
